version: '3.6'
services:
  postgres:
    image: postgres:14.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - '5432:5432'
    networks:
      - base-net
volumes:
  db_data:
networks:
  base-net:
    name: base-net
